name: roktalap
description: "A blood donation app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.8
  location: ^5.0.3
  provider: ^6.0.5
  http: ^1.1.0
  image_picker: ^1.2.0
  shared_preferences: ^2.2.0
  carousel_slider: ^5.1.1
  intl: ^0.19.0
  google_sign_in: ^6.1.5
  url_launcher: ^6.2.2
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
